### ISSUE TITLE
Bump version to 1.0.0

### ISSUE THREAD

**Issue by gdamore** [gdamore/less-fork#35]
0.9.49 was an illumos-core version number.  This is a separate repo now, and illumos-core is largely dead, so start with 1.0.0.  Its been stable for a while (indeed its used in *BSD now.)

**Comment by frgm** [comment]
https://github.com/gdamore/less-fork/releases :
> There aren’t any releases here

Could you create and push tag, please ?

**Comment by gdamore** [comment]
Yeah. Sure.
